Update MAIN.yml

diff --git a/.github/workflows/MAIN.yml b/.github/workflows/MAIN.yml
--- a/.github/workflows/MAIN.yml
+++ b/.github/workflows/MAIN.yml
@@ -1,6 +1,5 @@
 name: Generate Snake
 
-# Controls when the action will run. This action runs every 6 hours.
 on:
   schedule:
     - cron: "0 */6 * * *"
@@ -11,28 +10,25 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Checkout the repository
       - uses: actions/checkout@v2
 
-      # Generate the snake GIF and SVG
       - uses: Platane/snk@master
-        id: snake-gif
         with:
           github_user_name: NavindaHewawickrama
           gif_out_path: dist/github-contribution-grid-snake.gif
           svg_out_path: dist/github-contribution-grid-snake.svg
 
-      # Upload the snake GIF and SVG as artifacts
-      - name: Upload Snake Artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: snake-artifacts
-          path: dist/
+      - name: Check dist folder
+        run: |
+          ls -la dist/
+          if [ ! -d "dist" ]; then
+            echo "dist folder not found"
+            exit 1
+          fi
 
-      # Push the changes to the output branch for GitHub Pages
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
-          github_token: ${{ secrets.PAT_TOKEN }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: dist
           publish_branch: output
